### ISSUE TITLE
view context in store

### ISSUE THREAD

**Issue by HacksForHugs** [calblueprint/RMI#129]
Behavior:
- [x] changing routes should change view context. 
- [x] on initial load, view context should be set accordingly.

Files:
- [x] create view_context reducer
- [x] create function that handles type: `questionnaire_view + review_mode/edit_mode/delegate_mode`, `building_dashboard_view`,

- [x] create view_context actions
- [x] create actions for `set_questionnaire_edit_mode_view`, 
- [x] create actions for `set_questionnaire_review_mode_view`, 
- [x] create actions for `set_questionnaire_delegate_mode_view`, 
- [x] create actions for `set_building_dashboard_view`, 

- [x] add constants to constants file
```javascript
initial_state = 
{
  view_context: {
    buildings_view: false,
    questionnaire_view: {
      category: "all",
      edit_mode: "false",
      delegate_mode: "false",
      review_mode: "false"
    }
    building_dashboard_view: false
  }
}

function category_questionnaire_view_action(dispatch, category) {
  return {
    type: CATEGORY_QUESTIONNAIRE_VIEW,
    category,
    edit_mode: "true"
  }
}

function view_contexts (state=intial_state) {
  switch on type
  case type == CATEGORY_QUESTIONNAIRE_VIEW
  returning {
    ...initial_state,
    questionnaire_view: {
      ...questionnare_view,
      category: "this one",
      edit_mode: "true"
    }
  }
  default
  return state
}
```

**Comment by ethanlee16** [comment]
Closed in #149.
