### ISSUE TITLE
Status component for fetch states

### ISSUE THREAD

**Issue by kevintli** [calblueprint/RMI#160]
## Status component
Add a Status component that will be displayed under each answer. There are four possible states:

- [x] **By default (without trying to fetch)**: "_Answers will be automatically saved_"

- [x] **Failure**: displays message about connection and button to retry

![image](https://user-images.githubusercontent.com/2977329/36957047-92d3ff40-1fe6-11e8-937e-0a5192a8dbfd.png)

- [x] **Fetching**: displays "Saving..."

![image](https://user-images.githubusercontent.com/2977329/36957073-c169dd48-1fe6-11e8-834a-2d41070002e1.png)

- [x] **Success**: displays last updated. Use the `updated_at` time from store and the [momentjs](https://momentjs.com/) package.

![image](https://user-images.githubusercontent.com/2977329/36957105-ea37459e-1fe6-11e8-824e-53624f20732b.png)

## **Other Fixes**
- [ ] Make React-controlled inputs update even if no dependent option was hit
- [ ] Dispatch updateAnswer action only on blur, not whenever a key is pressed

**Comment by ethanlee16** [comment]
@kevintli Let's use last updated if it's available! Not super super important but would prefer ☺️
