### ISSUE TITLE
Question related models

### ISSUE THREAD

**Issue by HacksForHugs** [calblueprint/RMI#3]
- [x] **Question**
Model information:
- belongs_to: building_type
- belongs_to: parent_answer, polymorphic: true
- belongs_to: category
- has_many: dropdown_options
- has_many: answers
- alias_attribute :options :dropdown_options (note: this is the relationship between a question and its many possible answers)
- question_type	 (question details) (polymorphic association)
- parent_answer (parent_answer of question) (polymorphic association)
Schema information:
- t.string :text
- t.integer :status (enum: [draft, published])
- t.integer :integer 
- t.integer :min
- t.integer :max

- [x] **Building_Types**
Model Information
- has_many: buildings 
- has_many: questions
Schema Information
- t.string :name

- [x] **Categories**
Model Information
- has_many: questions
Schema Information
- t.string 📛 

Instantiate two options models
- [x] **Range_option**
Model information:
- has_one: question, as: :parent_answer
- belongs_to: range_question
Schema information:
- t.integer :min (the range that will trigger the specific child question)
- t.integer :max

- [x] **Dropdown_option**
Model information:
- has_one: question, as: :parent_answer (note: this is the CAUSAL relationship - i.e., the question that selecting this answer causes to appear - dependent questions!)
- belongs_to: dropdown_question
Schema information:
- t.string :text

**Comment by ethanlee16** [comment]
Complete in #13!
