### ISSUE TITLE
Entry point react + redux set up for RMI_user

### ISSUE THREAD

**Issue by HacksForHugs** [calblueprint/RMI#76]
- [x] create entry point index.jsx for after rmi_user login (rmi_user/show.html) . Import root reducer and top level app container (specified below.)
- [x] Create reducer files for rmi_user in the reducer folder: `building_types.jsx`. Rmi_user should also use the portfolio reducer.
- naming convention should follow "<container name>_reducer.jsx". This will make things a bit less confusing when we start pumping out container components. 
- reducer should have a SET_STATE action/case
- reducer should have an intial_state object defined and passed into the reducer as `state=initial_state` and be defaulted to in switch statement
- [x] Create root reducer file that combines any relevant reducers to rmi_user's flow and exports them as "RmiUserRootReducer" or something like that.
- [x] hydrate store  with state of rmi_user's building_types and portfolios data: 
- portfolios data includes building data for all portfolios. All keys for store objects should be the id of that object.
- building_types data includes data for each building_type rmi_user creates.
- structure for state tree should be:
```
building_types 
   ^ questions
      ^ options, answer
portfolios
   ^ buildings
      ^ questions 
         ^ options, answer                
```

- [x] create containers folder, and create container file for the app "RmiUserApp.jsx" that exports a blank const "RmiUserApp" or something like that.

**Comment by ethanlee16** [comment]
I'm actually started tackling #68 from RMI user with their state relation to questions. I'll put the other in Backlog for now.
