### ISSUE TITLE
User and portfolio models

### ISSUE THREAD

**Issue by HacksForHugs** [calblueprint/RMI#8]
- [x] 1. set up devise gem https://github.com/plataformatec/devise
- [x] 2. instantiate user models
**User** (inherits from Devise, relevant fields that we’ll likely be using below)
Schema Information
- t.string :name
- t.string :email
- t.string :phone
- t.string :encrypted_password

- [x] TODO: add verification for first/last name, email, phone number

Inheriting User Models
(relevant documentation: https://github.com/plataformatec/devise/wiki/How-to-Setup-Multiple-Devise-User-Models) 
Relevant Models
- [x] **RMIUser < User**	
- [x] **AssetManager < User**
Model information
- Has_many: portfolios
- [x] **BuildingOperator < User**

- [x] **Portfolio**
Model Information
- has_many: buildings
helongs_to: asset_manager_user
Schema information
- t.string name

- [x] **Buildings**
Model Information
- belongs_to: portfolio
- belongs_to: building_type
- has_one: location
- has_many: answers
Schema Information
- t.string :name
- t.string :contact_email

- [x] **Location**
Model information:
- belongs_to: buildings
- state enum
Schema information:
- t.string :address
- t.integer :state (enum needs to be populated)
- t.integer :zip

**Comment by JustinMi** [comment]
Arpan and I have a couple questions: 

1. Do we want email confirmations?
2. Do all recipients of the questionnaire need to create an account?

**Comment by JustinMi** [comment]
TODO: add verification for first/last name, email, phone number
